title: Missoula Cohort Model
author: Erik Kappleman
version: 1.0
settings:
  deathDir: Data\Deaths.csv
  birthDir: Data\Births.csv
  state: Montana
  county: Missoula
  year1: 2014
  year2: 2019
  year3: 2024
